baseurl: "http://sdqali.in"
title: "Sadique Ali"
layoutdir: "layouts"
contentdir: "content"
publishdir: "public"
indexes:
    category: "categories"
permalinks:
    blog: /blog/:year/:month/:day/:title/
metadataformat: "yaml"
params:
  description: "A blog about the Code I write and the Technologies I use. And other things that interest me."
PygmentsCodeFences: true
pygmentsstyle: "manni"
