baseurl: "https://sdqali.in"
title: "{code that works}"
layoutdir: "layouts"
contentdir: "content"
publishdir: "public"
taxonomies:
    category: "categories"
    tag: "tags"
    series: "series"
permalinks:
    blog: /blog/:year/:month/:day/:title/
metadataformat: "yaml"
params:
  description: "A blog about the Code I write and the Technologies I use. And other things that interest me."
  author: "Sadique Ali"
  keywords:
    - Programming
    - Software Development
    - Java Development
    - Coding
  googleAnalytics: "UA-86967633-1"
PygmentsCodeFences: true
pygmentsstyle: "manni"
enableRobotsTXT: true
